services:
  app:
    container_name: miniCRMApp
    build:
      context: ./
    ports:
      - "8081:8080"
    depends_on:
      - db
    restart: always
    networks:
      - crm-net

  db:
    image: postgres:16.3
    container_name: miniCRMDatabase
    environment:
      POSTGRES_DB: minicrmdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    networks:
      - crm-net

networks:
  crm-net:
    driver: bridge

volumes:
  db_data: