spring:
  application:
    name: miniCRM

  docker:
    compose:
      file: compose-dev.yaml

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/minicrmdb
    username: user
    password: pass

  liquibase:
    change-log: db/changelog-dev.yml
    contexts: dev

  server:
    port: 8080