spring:
  application:
    name: miniCRM

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/minicrmDB
    username: user
    password: pass

  liquibase:
    change-log: db/changelog-prod.yaml
    contexts: prod

  server:
    port: 8081