spring:
  application:
    name: miniCRM

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true

  liquibase:
    change-log: db/changelog-prod.yaml
    contexts: prod

server:
  port: ${PORT:8080}
